# Generated by Django 4.1.6 on 2023-06-10 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reparation_Machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('start', models.DateField()),
            ],
            options={
                'db_table': 'Machine',
            },
        ),
        migrations.CreateModel(
            name='MachineFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMachine', models.TextField(default='', max_length=20)),
            ],
            options={
                'db_table': 'Machine Family',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField(null=True)),
                ('closeDate', models.DateField(blank=True)),
                ('level', models.CharField(choices=[('LOW', 'Pane Low'), ('NORMAL', 'Pane Normal'), ('URGENT', 'Pane Urgent')], default='NORMAL', max_length=30)),
                ('titel', models.CharField(default='', max_length=30)),
                ('observation', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=1000)),
                ('status', models.CharField(choices=[('CLOSED', 'Ticket Closed'), ('IN_PROGRESS', 'Pane Normal')], default='IN_PROGRESS', max_length=20)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reparation_Machine.machine')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_technicien', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='machineFamily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reparation_Machine.machinefamily'),
        ),
    ]
