# Generated by Django 4.1.6 on 2023-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reparation_Machine', '0002_machine_machinefamily_ticket_machine_machinefamily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closeDate',
            field=models.DateField(null=True),
        ),
    ]
