# Generated by Django 4.1.6 on 2023-06-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reparation_Machine', '0004_alter_ticket_machine_alter_ticket_technicien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ticket Opened'), ('CLOSED', 'Ticket Closed'), ('IN_PROGRESS', 'Pane Normal')], default='IN_PROGRESS', max_length=20),
        ),
    ]
